#!/bin/bash
set -e

SCRIPT_DIR="$(realpath "$(dirname "${BASH_SOURCE[0]}")")"
SCRIPT_NAME="$(basename "$0")"

die() { echo "$*" 1>&2; exit 1; }
log() { echo "TEMPY-BUILD: $*"; }

ESP_IDF_DIR="${HOME}/.local/share/esp/esp-idf"
ESP_IDF_VERSION="v5.5.1"
ESP_MATTER_DIR="${HOME}/.local/share/matter/esp-matter"
ESP_TARGET="esp32h2"
ESP_SERIAL="/dev/ttyACM0"
ESP_SERIAL_ARG=()
[ -n "${ESP_SERIAL}" ] && ESP_SERIAL_ARG=(-p "${ESP_SERIAL}")

# --- Manufacturing / factory-data settings ------------------------------------
#
# These identify the product in the Matter Basic Information cluster and gate
# the DAC chain generated by esp-matter-mfg-tool. Keep VID/PID in sync with
# sdkconfig.defaults so the CD, the SPAKE2+ passcode derivation, and the
# device attestation chain all reference the same product identity.
MFG_VID="0xFFF1"
MFG_PID="0x8000"
MFG_VENDOR_NAME="PsychicThings"
MFG_PRODUCT_NAME="Tempy H2-280 Temperature Sensor"
MFG_PRODUCT_LABEL="Tempy Temperature Sensor"
MFG_PRODUCT_URL="https://github.com/compenguy/tempy"
MFG_HW_VERSION=1
MFG_HW_VERSION_STRING="SM-H2-280-00"
# Serial numbers are auto-generated per unit when --serial-num is omitted.

# Where in flash the fctry partition lives. Must match partitions.csv:
# `fctry, data, nvs, 0x3E0000, 0x6000`. If you ever repartition, update
# both places. Size isn't referenced here because esptool.py's write_flash
# takes just an offset; mfg_tool builds a partition binary sized to fit.
FCTRY_OFFSET="0x3E0000"

# Where in flash the runtime `nvs` partition lives. Must match partitions.csv:
# `nvs, data, nvs, 0x10000, 0xC000`. --reset-fabric erases just this range so
# the device forgets Matter fabrics/ACLs/subscriptions without dropping the
# per-unit factory credentials.
NVS_OFFSET="0x10000"
NVS_SIZE="0xC000"

MFG_OUT_DIR="${SCRIPT_DIR}/build/mfg"

function init_esp_idf() {
	(
		if ! [ -d "${ESP_IDF_DIR}" ] || ! [ -d "${ESP_IDF_DIR}"/.git ] ; then
			log "Cloning esp-idf repository..."
			mkdir -p "${ESP_IDF_DIR}"/..
		 	cd "${ESP_IDF_DIR}"/..
			git clone -b "${ESP_IDF_VERSION}" --recursive https://github.com/espressif/esp-idf.git
		 	cd "${ESP_IDF_DIR}"/
		fi
		cd "${ESP_IDF_DIR}"/
		log "Refreshing esp-idf submodules..."
		git submodule update --init --depth 1
		log "Refreshing esp-idf components..."
		./install.sh
		log "Setting esp-idf target device..."
		source "${ESP_IDF_DIR}"/export.sh
		idf.py set-target "${ESP_TARGET}"
	)
}

function activate_esp_idf() {
	#init_esp_idf
	log "Activating esp-idf..."
	source "${ESP_IDF_DIR}"/export.sh
}

function init_esp_matter() {
	(
		if ! [ -d "${ESP_MATTER_DIR}" ] || ! [ -d "${ESP_MATTER_DIR}"/.git ] ; then
			log "Cloning esp-matter repository..."
			mkdir -p "${ESP_MATTER_DIR}"/..
			cd "${ESP_MATTER_DIR}"/..
			git clone --depth 1 https://github.com/espressif/esp-matter.git
			cd "${ESP_MATTER_DIR}"
		fi
		cd "${ESP_MATTER_DIR}"
		log "Refreshing esp-matter submodules..."
		git submodule update --init --depth 1
		log "Refreshing CHIP submodules..."
		cd ./connectedhomeip/connectedhomeip
		./scripts/checkout_submodules.py --platform esp32 linux --shallow
		cd ../..
		log "Refreshing esp-matter components..."
		./install.sh
	)
}

function activate_esp_matter() {
	#init_esp_matter
	log "Activating esp-matter..."
	source "${ESP_MATTER_DIR}"/export.sh
}

# Prompt for a yes/no answer. Defaults to "no" on empty input. Returns 0 for
# yes, 1 for no. In non-interactive shells (no controlling TTY) also returns 1
# so a CI run never silently agrees to a long-running build.
function _prompt_yn() {
	local question="$1"
	if ! [ -t 0 ]; then
		log "Non-interactive shell; skipping prompt: ${question}"
		return 1
	fi
	local reply
	read -r -p "${question} [y/N] " reply
	[[ "${reply}" =~ ^[Yy] ]]
}

# Populate the MFG_* paths pointing at CHIP's in-tree test PAI + CD-signing
# credentials. These are the "test root of trust" chain -- chip-tool accepts
# them because it ships those roots pre-trusted; a production commissioner
# (Apple Home, Google Home, SmartThings, ...) will reject the resulting DACs
# because the CSA test roots aren't in their attestation stores. That's the
# right trade-off for "everything short of certification": each unit gets a
# real per-device DAC, but the chain still terminates in a public test root.
function _matter_test_paths() {
	local sdk="${ESP_MATTER_DIR}/connectedhomeip/connectedhomeip"
	MFG_PAI_CERT="${sdk}/credentials/test/attestation/Chip-Test-PAI-FFF1-8000-Cert.pem"
	MFG_PAI_KEY="${sdk}/credentials/test/attestation/Chip-Test-PAI-FFF1-8000-Key.pem"
	MFG_CD_SIGNING_CERT="${sdk}/credentials/test/certification-declaration/Chip-Test-CD-Signing-Cert.pem"
	MFG_CD_SIGNING_KEY="${sdk}/credentials/test/certification-declaration/Chip-Test-CD-Signing-Key.pem"
	MFG_CHIP_CERT="${sdk}/out/host/chip-cert"
	MFG_CD_OUT="${MFG_OUT_DIR}/Tempy-CD-${MFG_VID#0x}-${MFG_PID#0x}.der"
}

# Ensure esp-matter-mfg-tool is importable from the currently-active Python.
# Installs it into the esp-idf virtualenv on first use. Fails with a helpful
# message if the pip install can't build wheels (usually a missing
# python3-dev or libssl-dev on the host).
function _ensure_mfg_tool() {
	if command -v esp-matter-mfg-tool >/dev/null 2>&1; then
		return 0
	fi
	log "esp-matter-mfg-tool not found; installing from PyPI..."
	if ! python3 -m pip install --quiet esp-matter-mfg-tool; then
		die "Failed to install esp-matter-mfg-tool. If the pip log mentions building cffi or cryptography from source, install the OS packages python3-dev and libssl-dev (or the equivalents for your distro) and retry."
	fi
	command -v esp-matter-mfg-tool >/dev/null 2>&1 \
		|| die "esp-matter-mfg-tool installed but not on PATH -- something is wrong with the esp-idf virtualenv."
}

# Ensure the CHIP host tool `chip-cert` exists at the expected path. It's
# needed to synthesize a Certification Declaration for our VID/PID (no
# ready-made CD ships for FFF1-8000). If missing, prompt the user before
# spending a few minutes on the host build; skip in non-interactive shells.
function _ensure_chip_cert() {
	_matter_test_paths
	if [ -x "${MFG_CHIP_CERT}" ]; then
		return 0
	fi
	log "chip-cert not found at ${MFG_CHIP_CERT}."
	log "It's a small (~2-3 min) host build under the CHIP Linux SDK."
	if ! _prompt_yn "Build chip-cert now?"; then
		die "Cannot generate a Certification Declaration without chip-cert. Re-run --mfg-gen once chip-cert is built."
	fi
	log "Building chip-cert (this pulls a few CHIP submodules on first run)..."
	(
		set -e
		local sdk="${ESP_MATTER_DIR}/connectedhomeip/connectedhomeip"
		cd "${sdk}"
		# activate.sh sets up gn / ninja / pigweed for the CHIP tree.
		# It re-execs into its own venv and clobbers PYTHONHOME, so run
		# it in a subshell to protect the esp-idf environment.
		source scripts/activate.sh
		gn gen out/host
		ninja -C out/host chip-cert
	) || die "chip-cert build failed. See the log above; usually a missing OS dep (libssl-dev, pkg-config, ninja, ...)."
	[ -x "${MFG_CHIP_CERT}" ] || die "chip-cert build reported success but the binary isn't at ${MFG_CHIP_CERT}."
	log "chip-cert built successfully."
}

# Generate a Certification Declaration for our VID/PID once, signed with
# the CHIP test CD-signing key. Idempotent: skip if the file already
# exists. There is no in-tree Chip-Test-CD-FFF1-8000.der (only FFF2/FFF3
# variants), so we have to synthesize one -- which is exactly what CHIP
# itself does to produce those FFFx test CDs.
function mfg_gen_cd() {
	_ensure_chip_cert
	mkdir -p "${MFG_OUT_DIR}"
	if [ -f "${MFG_CD_OUT}" ]; then
		log "CD already exists at ${MFG_CD_OUT}, skipping generation"
		return 0
	fi
	log "Generating Certification Declaration for VID=${MFG_VID} PID=${MFG_PID}..."
	"${MFG_CHIP_CERT}" gen-cd \
		--format-version 1 \
		--vendor-id "${MFG_VID}" \
		--product-id "${MFG_PID}" \
		--device-type-id 0x0302 \
		--certificate-id "CSA00000SWC00000-00" \
		--security-level 0 \
		--security-info 0 \
		--version-number 1 \
		--certification-type 0 \
		--key "${MFG_CD_SIGNING_KEY}" \
		--cert "${MFG_CD_SIGNING_CERT}" \
		--out "${MFG_CD_OUT}"
	log "CD written to ${MFG_CD_OUT}"
}

# Generate one (or N) factory partition binaries. Each contains a
# unique passcode, discriminator, serial number, and DAC signed by the
# project PAI. Output lands in build/mfg/out/<vid_pid>/<uuid>/, with
# the flashable image at build/mfg/out/<vid_pid>/<uuid>/<uuid>-partition.bin
# and the onboarding codes / QR PNG alongside.
function mfg_gen() {
	local count="${1:-1}"
	_ensure_mfg_tool
	mfg_gen_cd
	mkdir -p "${MFG_OUT_DIR}"
	log "Generating ${count} factory partition(s) into ${MFG_OUT_DIR}/out/..."
	(
		cd "${MFG_OUT_DIR}"
		esp-matter-mfg-tool \
			-n "${count}" \
			-v "${MFG_VID}" -p "${MFG_PID}" \
			--vendor-name    "${MFG_VENDOR_NAME}" \
			--product-name   "${MFG_PRODUCT_NAME}" \
			--product-label  "${MFG_PRODUCT_LABEL}" \
			--product-url    "${MFG_PRODUCT_URL}" \
			--hw-ver         "${MFG_HW_VERSION}" \
			--hw-ver-str     "${MFG_HW_VERSION_STRING}" \
			--enable-rotating-device-id \
			--pai \
			-k  "${MFG_PAI_KEY}" \
			-c  "${MFG_PAI_CERT}" \
			-cd "${MFG_CD_OUT}"
	)
	log "Done. Per-unit onboarding codes: ${MFG_OUT_DIR}/out/*/*-onb_codes.csv"
	log "Per-unit QR-code PNGs:           ${MFG_OUT_DIR}/out/*/*-qrcode.png"
}

# Flash a factory partition binary to the fctry offset. Defaults to the
# most-recently-generated unit; pass an explicit path when provisioning
# from a batch. Assumes the app has already been written by --flash /
# --full-flash; the fctry partition is only touched here so a firmware
# reflash doesn't overwrite per-unit credentials.
function mfg_flash() {
	local bin="${1:-}"
	if [ -z "${bin}" ]; then
		# mfg_tool nests output as out/<vid_pid>/<uuid>/<uuid>-partition.bin,
		# so we glob three levels below MFG_OUT_DIR/out.
		bin="$(ls -t "${MFG_OUT_DIR}"/out/*/*/*-partition.bin 2>/dev/null | head -n1 || true)"
		[ -n "${bin}" ] || die "No factory partition binary found. Run '${SCRIPT_NAME} --mfg-gen' first."
	fi
	[ -f "${bin}" ] || die "Factory partition binary not found: ${bin}"
	log "Flashing ${bin} to ${ESP_SERIAL} @ ${FCTRY_OFFSET}..."
	esptool.py "${ESP_SERIAL_ARG[@]}" -c "${ESP_TARGET}" write_flash "${FCTRY_OFFSET}" "${bin}"
	log "Factory partition flashed. Reset the device to pick up new credentials."
}

# Erase just the runtime `nvs` partition, forcing the device to forget
# every commissioned fabric, ACL, subscription, and check-in registration.
# Leaves the `fctry` partition (per-unit DAC/PAI/CD/passcode) intact, so
# the device can be re-commissioned without re-running mfg_tool. Also
# leaves the app image alone, so this is much faster than --full-flash.
function reset_fabric() {
	if ! _prompt_yn "Erase runtime NVS at ${NVS_OFFSET} (${NVS_SIZE} bytes)? This forgets every commissioned fabric."; then
		die "Aborted."
	fi
	log "Erasing runtime NVS partition..."
	esptool.py "${ESP_SERIAL_ARG[@]}" -c "${ESP_TARGET}" erase_region "${NVS_OFFSET}" "${NVS_SIZE}"
	log "Runtime NVS erased. Device will boot as un-commissioned; factory credentials preserved."
}

# Default values for command-line arguments
ARG_CONFIG=0
ARG_RECONFIG=0
ARG_BUILD=0
ARG_FLASH=0
ARG_FULLCLEAN=0
ARG_FULL_FLASH=0
ARG_MONITOR=0
ARG_MFG_GEN=0
ARG_MFG_GEN_COUNT=1
ARG_MFG_FLASH=0
ARG_MFG_FLASH_PATH=""
ARG_RESET_FABRIC=0

# Argument parsing
usage() {
cat << EOF
Usage: ${SCRIPT_NAME} [config-args] [build-args] [program-args] [debug-args]
General Arguments:
  -h, --help		explanation of command line argument and environment
            		variable options
Configuration Arguments:
      --full-clean	invoke idf.py fullclean
  -c, --menuconfig	invoke idf.py menuconfig
  -r, --reconfigure	invoke idf.py reconfigure
Build Arguments:
  -b, --build		invoke idf.py to build the specified target
Programming Arguments:
  -F, --full-flash	wipes out the entire flash and starts fresh (\`erase-flash\`)
  -f, --flash		write the built firmware to flash
Debugging Arguments:
  -m, --monitor		starts serial debug montoring of device via the USB serial interface (ESP_SERIAL=${ESP_SERIAL})
Factory-Data Arguments:
      --mfg-gen [N]	generate N per-unit factory partition binaries under
            		build/mfg/out/ (default N=1) using esp-matter-mfg-tool.
            		Also synthesizes a signed CD for the project VID/PID on
            		first run (prompting to build chip-cert if needed).
      --mfg-flash [BIN]	flash a factory partition binary to the fctry offset
            		(default: newest built). Leaves the app image and
            		runtime NVS untouched.
      --reset-fabric	erase the runtime NVS partition (fabric table, ACLs,
            		subscriptions) without touching factory credentials or
            		the app image. Prompts for confirmation.
EOF
}

while [[ $# -gt 0 ]]; do
	case $1 in
		-b|--build)
			shift
			ARG_BUILD=1
			;;
		-c|--menuconfig)
			shift
			ARG_CONFIG=1
			;;
		-r|--reconfigure)
			shift
			ARG_RECONFIG=1
			;;
		-f|--flash)
			shift
			ARG_FLASH=1
			;;
		--full-clean)
			shift
			ARG_FULLCLEAN=1
			;;
		-F|--full-flash)
			shift
			ARG_FULL_FLASH=1
			;;
		-m|--monitor)
			shift
			ARG_MONITOR=1
			;;
		--mfg-gen)
			shift
			ARG_MFG_GEN=1
			if [[ $# -gt 0 && "$1" =~ ^[0-9]+$ ]]; then
				ARG_MFG_GEN_COUNT="$1"
				shift
			fi
			;;
		--mfg-flash)
			shift
			ARG_MFG_FLASH=1
			if [[ $# -gt 0 && "$1" != -* ]]; then
				ARG_MFG_FLASH_PATH="$1"
				shift
			fi
			;;
		--reset-fabric)
			shift
			ARG_RESET_FABRIC=1
			;;
		-h|--help)
			usage
			exit 0
			;;
		*)
			usage
			echo ""
			die "Unrecognized argument '$1'"
			;;
	esac
done

# Task tracking variables
CONFIG_ACTIVITY=0
RECONFIG_ACTIVITY=0
BUILD_ACTIVITY=0
FLASH_ACTIVITY=0
MONITOR_ACTIVITY=0
MFG_ACTIVITY=0

activate_esp_idf
activate_esp_matter

# Perform the requested work
echo "Task(s) starting at $(date --rfc-3339=seconds)"
echo "Configured build settings:"
echo "    ESP target=${ESP_TARGET}"
echo "    esp-idf version=${ESP_IDF_VERSION}"
if [ "${ARG_FULLCLEAN}" -ne 0 ]; then
	log "Cleaning project..."
	(
		cd "${SCRIPT_DIR}"
		idf.py fullclean
	)
	CONFIG_ACTIVITY=1
fi
if [ "${ARG_CONFIG}" -ne 0 ]; then
	log "Configuring project..."
	(
		cd "${SCRIPT_DIR}"
		idf.py menuconfig
	)
	CONFIG_ACTIVITY=1
fi
if [ "${ARG_RECONFIG}" -ne 0 ]; then
	log "Reconfiguring project..."
	(
		cd "${SCRIPT_DIR}"
		idf.py reconfigure
	)
	RECONFIG_ACTIVITY=1
fi
if [ "${ARG_BUILD}" -ne 0 ]; then
	log "Building project..."
	(
		cd "${SCRIPT_DIR}"
		idf.py build
	)
	BUILD_ACTIVITY=1
fi
if [ "${ARG_FLASH}" -ne 0 ]; then
	log "Flashing project..."
	(
		cd "${SCRIPT_DIR}"
		idf.py "${ESP_SERIAL_ARG[@]}" flash
	)
	FLASH_ACTIVITY=1
fi
if [ "${ARG_FULL_FLASH}" -ne 0 ]; then
	log "Full-storage flashing project..."
	(
		cd "${SCRIPT_DIR}"
		idf.py "${ESP_SERIAL_ARG[@]}" erase-flash
		idf.py "${ESP_SERIAL_ARG[@]}" flash
	)
	FLASH_ACTIVITY=1
fi
if [ "${ARG_MFG_GEN}" -ne 0 ]; then
	log "Generating factory partition(s)..."
	mfg_gen "${ARG_MFG_GEN_COUNT}"
	MFG_ACTIVITY=1
fi
if [ "${ARG_MFG_FLASH}" -ne 0 ]; then
	log "Flashing factory partition..."
	mfg_flash "${ARG_MFG_FLASH_PATH}"
	MFG_ACTIVITY=1
fi
if [ "${ARG_RESET_FABRIC}" -ne 0 ]; then
	log "Resetting fabric state..."
	reset_fabric
	MFG_ACTIVITY=1
fi
if [ "${ARG_MONITOR}" -ne 0 ]; then
	log "Monitoring device..."
	(
		cd "${SCRIPT_DIR}"
		idf.py "${ESP_SERIAL_ARG[@]}" monitor
	)
	MONITOR_ACTIVITY=1
fi

# Wrap-up
if [[ ${CONFIG_ACTIVITY} -eq 0 ]] && [[ ${RECONFIG_ACTIVITY} -eq 0 ]] \
	&& [[ ${BUILD_ACTIVITY} -eq 0 ]] && [[ ${FLASH_ACTIVITY} -eq 0 ]] \
	&& [[ ${MONITOR_ACTIVITY} -eq 0 ]] && [[ ${MFG_ACTIVITY} -eq 0 ]]; then
	usage
	echo ""
	echo "Nothing to do! Did you mean to specify --menuconfig, --build, --flash, or --monitor?"
else
	echo "Task(s) completed at $(date --rfc-3339=seconds)"
	echo "Configured build settings:"
	echo "    ESP target=${ESP_TARGET}"
	echo "    esp-idf version=${ESP_IDF_VERSION}"
fi

