#include <driver/gpio.h>
#include <driver/i2c.h>
#include <esp_err.h>
#include <esp_log.h>
#include <freertos/FreeRTOS.h>
#include <freertos/task.h>
#include <driver/i2c_master.h>
#include <esp_matter_core.h>
#include <ble_beacon.h>
#include <math.h> // required for NAN constant

#include "sdkconfig.h" // generated by "make menuconfig"
#include "app_priv.h"
#include "bme280.h"

#define TAG_BME280 "APP_BME280"

// Advertising duration per reading. 50ms is enough for 2-3 advertisements
// at slow intervals, sufficient for nearby receivers to catch the beacon.
#define ADV_TIME_MS 50

#define I2C_PORT -1 // autoselect

#define I2C_BME_ADDRESS CONFIG_BME280_I2C_ADDRESS
#define I2C_BME_CLK_FREQ 50000

// esp i2c handles
static i2c_master_bus_handle_t bus_handle;
static bme280_t bme;

// matter data
static uint16_t temp_endpoint_id;
static uint16_t humidity_endpoint_id;

// matter callbacks
using namespace esp_matter;
using namespace esp_matter::endpoint;
using namespace chip::app::Clusters;

// Application cluster specification, 7.18.2.11. Temperature
// represents a temperature on the Celsius scale with a resolution of 0.01°C.
// temp = (temperature in °C) x 100
static void matter_temp_sensor_notification(uint16_t endpoint_id, float temp)
{
    // Schedule the attribute update onto the Matter thread. ScheduleLambda is
    // thread-safe, so we intentionally do not take chip_stack_lock here.
    chip::DeviceLayer::SystemLayer().ScheduleLambda([endpoint_id, temp]() {
        attribute_t *attribute = attribute::get(endpoint_id,
                                                TemperatureMeasurement::Id,
                                                TemperatureMeasurement::Attributes::MeasuredValue::Id);
        if (attribute == nullptr) {
            ESP_LOGW(TAG_BME280, "Temperature attribute not found on endpoint %u", endpoint_id);
            return;
        }

        esp_matter_attr_val_t val = esp_matter_invalid(nullptr);
        attribute::get_val(attribute, &val);
        val.val.i16 = static_cast<int16_t>(temp * 100);

        attribute::update(endpoint_id, TemperatureMeasurement::Id,
                          TemperatureMeasurement::Attributes::MeasuredValue::Id, &val);
    });
}

// Application cluster specification, 2.6.4.1. MeasuredValue Attribute
// represents the humidity in percent.
// humidity = (humidity in %) x 100
static void matter_humidity_sensor_notification(uint16_t endpoint_id, float humidity)
{
    // Schedule the attribute update onto the Matter thread. See note above.
    chip::DeviceLayer::SystemLayer().ScheduleLambda([endpoint_id, humidity]() {
        attribute_t *attribute = attribute::get(endpoint_id,
                                                RelativeHumidityMeasurement::Id,
                                                RelativeHumidityMeasurement::Attributes::MeasuredValue::Id);
        if (attribute == nullptr) {
            ESP_LOGW(TAG_BME280, "Humidity attribute not found on endpoint %u", endpoint_id);
            return;
        }

        esp_matter_attr_val_t val = esp_matter_invalid(nullptr);
        attribute::get_val(attribute, &val);
        val.val.u16 = static_cast<uint16_t>(humidity * 100);

        attribute::update(endpoint_id, RelativeHumidityMeasurement::Id,
                          RelativeHumidityMeasurement::Attributes::MeasuredValue::Id, &val);
    });
}

static void beacon_weather_sensor_broadcast(float temperature, float humidity, float pressure)
{
    weather_data_t sensor_data = {
        .temperature = temperature,
        .humidity = humidity,
        .pressure = pressure,
    };
    esp_err_t err = ble_beacon_start(&sensor_data, ADV_TIME_MS);
    if (err != ESP_OK) {
        ESP_LOGW(TAG_BME280, "BLE beacon broadcast failed: %s", esp_err_to_name(err));
    }
}

static void i2c_master_init(void)
{
    // Create I2C master bus
    i2c_master_bus_config_t i2c_mst_config = {
        .i2c_port = I2C_PORT,
        .sda_io_num = (gpio_num_t)CONFIG_BME280_I2C_SDA_PIN,
        .scl_io_num = (gpio_num_t)CONFIG_BME280_I2C_SCL_PIN,
        .clk_source = I2C_CLK_SRC_DEFAULT,
        .glitch_ignore_cnt = 7,
        .flags {
            // Set this to false if you've wired suitable pullups to scl/sda
            // note that the internal pullup is not strong enough for high speed operation
            .enable_internal_pullup = true,
            .allow_pd = true,
        }
    };

    ESP_LOGD(TAG_BME280, "Attaching to primary I2C bus...");
    ESP_ERROR_CHECK(i2c_new_master_bus(&i2c_mst_config, &bus_handle));

    // Probe for BME device on bus before continuing
    ESP_LOGI(TAG_BME280, "Probing for BME280 on I2C bus at 0x%02X...", I2C_BME_ADDRESS);
    esp_err_t probe_err = i2c_master_probe(bus_handle, I2C_BME_ADDRESS, 100);
    if (probe_err != ESP_OK) {
        ESP_LOGE(TAG_BME280, "BME280 not found at 0x%02X! Check wiring (SDA=%d, SCL=%d). Error: %s",
                 I2C_BME_ADDRESS, CONFIG_BME280_I2C_SDA_PIN, CONFIG_BME280_I2C_SCL_PIN,
                 esp_err_to_name(probe_err));
        ESP_ERROR_CHECK(probe_err);
    }
    ESP_LOGI(TAG_BME280, "BME280 detected on I2C bus");
}

static void task_bme280_forced_mode(void *ignore)
{
    float t, h;
    // Allow some time for the Matter thread to finish initializing before
    // scheduling the first attribute update.
    vTaskDelay(pdMS_TO_TICKS(500));
    while (1) {
        esp_err_t err = bme280_read_temp_humidity(&bme, &t, &h);
        if (err == ESP_OK) {
            ESP_LOGD(TAG_BME280, "Temperature: %.2f C", t);
            ESP_LOGD(TAG_BME280, "Humidity:    %.1f %%RH", h);
            beacon_weather_sensor_broadcast(t, h, NAN);
            // only send matter notifications if we have matter subscribers
            if (chip::app::InteractionModelEngine::GetInstance()->GetNumActiveReadHandlers(
                    chip::app::ReadHandler::InteractionType::Subscribe) >  0) {
                matter_temp_sensor_notification(temp_endpoint_id, t);
                matter_humidity_sensor_notification(humidity_endpoint_id, h);
            }
        } else {
            ESP_LOGW(TAG_BME280, "Read failed: %s", esp_err_to_name(err));
        }
        vTaskDelay(pdMS_TO_TICKS(CONFIG_DELAY_BETWEEN_SENSOR_READINGS_MS));
    }
}

void bme280_app_init(endpoint_t *temp_sensor_ep, endpoint_t *humidity_sensor_ep)
{
    // init for sending sensor data via beacons
    ESP_LOGI(TAG_BME280, "Initializing BLE beacon component");
    ESP_ERROR_CHECK(ble_beacon_init());

    // init for sending sensor data via matter+thread
    temp_endpoint_id = endpoint::get_id(temp_sensor_ep);
    humidity_endpoint_id = endpoint::get_id(humidity_sensor_ep);

    // init sensor on i2c
    i2c_master_init();
    ESP_LOGI(TAG_BME280, "Initializing BME280...");
    ESP_ERROR_CHECK(bme280_init(&bme, bus_handle, I2C_BME_ADDRESS, I2C_BME_CLK_FREQ));

    ESP_LOGI(TAG_BME280, "Scheduling BME280 to take regular readings...");
    BaseType_t rc = xTaskCreate(&task_bme280_forced_mode, "bme280_forced_mode",
                                3072, nullptr, 6, nullptr);
    if (rc != pdPASS) {
        ESP_LOGE(TAG_BME280, "Failed to create BME280 task (rc=%d)", (int)rc);
    }
}

