#include <driver/gpio.h>
#include <driver/i2c.h>
#include <esp_err.h>
#include <esp_log.h>
#include <freertos/task.h>
#include <driver/i2c_master.h>
#include <driver/bme280.h>

#include "sdkconfig.h" // generated by "make menuconfig"
#include "app_priv.h"

#define TAG_BME280 "BME280"

#define I2C_PORT -1 // autoselect
#define I2C_TIMEOUT -1 // wait forever

#define I2C_BME_CLK_FREQ 100000
#define I2C_BME_ADDRESS 0x77 // default for device
#define I2C_BME_SAMPLE_COUNT 50

// esp i2c handles
static i2c_master_bus_handle_t bus_handle;
static i2c_master_dev_handle_t bme_handle;

// bme280 function pointers

// BME280_INTF_RET_TYPE (*bme280_write_fptr_t)(uint8_t reg_addr, const uint8_t *reg_data, uint32_t len, void *intf_ptr);
static BME280_INTF_RET_TYPE BME280_I2C_write(uint8_t reg_addr, const uint8_t *reg_data, uint32_t len, void *intf_ptr)
{
    return i2c_master_transmit(bme_handle, reg_data, len, I2C_TIMEOUT);
}

// BME280_INTF_RET_TYPE (*bme280_read_fptr_t)(uint8_t reg_addr, uint8_t *reg_data, uint32_t len, void *intf_ptr);
static BME280_INTF_RET_TYPE BME280_I2C_read(uint8_t reg_addr, uint8_t *reg_data, uint32_t len, void *intf_ptr)
{
    return i2c_master_receive(bme_handle, reg_data, len, I2C_TIMEOUT);
}

// void (*bme280_delay_us_fptr_t)(uint32_t period, void *intf_ptr);
static void BME280_delay_usec(uint32_t usec, void *intf_ptr)
{
    int32_t msec = usec / 1000;
    vTaskDelay(msec/portTICK_PERIOD_MS);
}

// bme280 driver data
static struct bme280_dev bme_dev = {
    .intf = BME280_I2C_INTF,
    .intf_ptr = &bme_handle,
    .read = (bme280_read_fptr_t)BME280_I2C_read,
    .write = (bme280_write_fptr_t)BME280_I2C_write,
    .delay_us = (bme280_delay_us_fptr_t)BME280_delay_usec
};
static uint32_t bme280_meas_period;

// matter data
static uint16_t temp_endpoint_id;
static uint16_t humidity_endpoint_id;

// matter callbacks
using namespace esp_matter;
using namespace esp_matter::endpoint;
using namespace chip::app::Clusters;

// Application cluster specification, 7.18.2.11. Temperature
// represents a temperature on the Celsius scale with a resolution of 0.01°C.
// temp = (temperature in °C) x 100
static void temp_sensor_notification(uint16_t endpoint_id, float temp, void *user_data)
{
    // schedule the attribute update so that we can report it from matter thread
    chip::DeviceLayer::SystemLayer().ScheduleLambda([endpoint_id, temp]() {
        attribute_t * attribute = attribute::get(endpoint_id,
                                                 TemperatureMeasurement::Id,
                                                 TemperatureMeasurement::Attributes::MeasuredValue::Id);

        esp_matter_attr_val_t val = esp_matter_invalid(NULL);
        attribute::get_val(attribute, &val);
        val.val.i16 = static_cast<int16_t>(temp * 100);

        attribute::update(endpoint_id, TemperatureMeasurement::Id, TemperatureMeasurement::Attributes::MeasuredValue::Id, &val);
    });
}

// Application cluster specification, 2.6.4.1. MeasuredValue Attribute
// represents the humidity in percent.
// humidity = (humidity in %) x 100
static void humidity_sensor_notification(uint16_t endpoint_id, float humidity, void *user_data)
{
    // schedule the attribute update so that we can report it from matter thread
    chip::DeviceLayer::SystemLayer().ScheduleLambda([endpoint_id, humidity]() {
        attribute_t * attribute = attribute::get(endpoint_id,
                                                 RelativeHumidityMeasurement::Id,
                                                 RelativeHumidityMeasurement::Attributes::MeasuredValue::Id);

        esp_matter_attr_val_t val = esp_matter_invalid(NULL);
        attribute::get_val(attribute, &val);
        val.val.u16 = static_cast<uint16_t>(humidity * 100);

        attribute::update(endpoint_id, RelativeHumidityMeasurement::Id, RelativeHumidityMeasurement::Attributes::MeasuredValue::Id, &val);
    });
}

void i2c_master_init()
{
    i2c_master_bus_config_t i2c_mst_config = {
        .i2c_port = I2C_PORT,
        .sda_io_num = (gpio_num_t)CONFIG_BME280_I2C_SDA_PIN,
        .scl_io_num = (gpio_num_t)CONFIG_BME280_I2C_SCL_PIN,
        .clk_source = I2C_CLK_SRC_DEFAULT,
        .glitch_ignore_cnt = 7,
        .flags {
            // Set this to false if you've wired suitable pullups to scl/sda
            // note that the internal pullup is not strong enough for high speed operation
            .enable_internal_pullup = true,
            .allow_pd = true,
        }
    };

    ESP_ERROR_CHECK(i2c_new_master_bus(&i2c_mst_config, &bus_handle));

    // Probe for BME device on bus before continuing
    ESP_ERROR_CHECK(i2c_master_probe(bus_handle, I2C_BME_ADDRESS, -1));

    // Setup config structure for communicating with BME
    i2c_device_config_t bme_cfg = {
        .dev_addr_length = I2C_ADDR_BIT_LEN_7,
        .device_address = I2C_BME_ADDRESS,
        .scl_speed_hz = I2C_BME_CLK_FREQ,
    };

    ESP_ERROR_CHECK(i2c_master_bus_add_device(bus_handle, &bme_cfg, &bme_handle));
}

void i2c_bme280_init() {
    ESP_ERROR_CHECK(bme280_init(&bme_dev));

    struct bme280_settings settings;
    ESP_ERROR_CHECK(bme280_get_sensor_settings(&settings, &bme_dev));

    /* Configuring the over-sampling rate, filter coefficient and standby time */
    /* Overwrite the desired settings */
    settings.filter = BME280_FILTER_COEFF_OFF;

    /* Over-sampling rate for humidity, temperature and pressure */
    settings.osr_h = BME280_OVERSAMPLING_1X;
    settings.osr_p = BME280_OVERSAMPLING_1X;
    settings.osr_t = BME280_OVERSAMPLING_1X;

    /* Setting the standby time */
    settings.standby_time = BME280_STANDBY_TIME_0_5_MS;

    ESP_ERROR_CHECK(bme280_set_sensor_settings(BME280_SEL_ALL_SETTINGS, &settings, &bme_dev));

    /* Always set the power mode after setting the configuration */
    ESP_ERROR_CHECK(bme280_set_sensor_mode(BME280_POWERMODE_FORCED, &bme_dev));

    /* Calculate measurement time in microseconds */
    ESP_ERROR_CHECK(bme280_cal_meas_delay(&bme280_meas_period, &settings));

    ESP_LOGI(TAG_BME280, "Measurement time : %lu us", bme280_meas_period);
}

void task_bme280_forced_mode(void *ignore) {
    int8_t idx = 0;
    uint8_t status_reg;
    struct bme280_data comp_data;

    while (idx < I2C_BME_SAMPLE_COUNT)
    {
        ESP_ERROR_CHECK(bme280_get_regs(BME280_REG_STATUS, &status_reg, 1, &bme_dev));

        if (status_reg & BME280_STATUS_MEAS_DONE)
        {
            /* Measurement time delay given to read sample */
            bme_dev.delay_us(bme280_meas_period, bme_dev.intf_ptr);

            /* Read compensated data */
            ESP_ERROR_CHECK(bme280_get_sensor_data(BME280_TEMP | BME280_HUM, &comp_data, &bme_dev));

#ifndef BME280_DOUBLE_ENABLE
            comp_data.temperature = comp_data.temperature / 100;
            comp_data.humidity = comp_data.humidity / 1000;
#endif

#ifdef BME280_DOUBLE_ENABLE
            ESP_LOGI(TAG_BME280, "Temperature[%d]:   %lf deg C\n", idx, comp_data.temperature);
            ESP_LOGI(TAG_BME280, "Humidity   [%d]:   %lf %%RH\n", idx, comp_data.humidity);
#else
            ESP_LOGI(TAG_BME280, "Temperature[%d]:   %ld deg C\n", idx, (long int)comp_data.temperature);
            ESP_LOGI(TAG_BME280, "Humidity   [%d]:   %lu %%RH\n", idx, (long unsigned int)comp_data.humidity);
#endif
            temp_sensor_notification(temp_endpoint_id, comp_data.temperature, NULL);
            humidity_sensor_notification(humidity_endpoint_id, comp_data.humidity, NULL);
            idx++;
        }
    }
}

void bme280_app_init(endpoint_t *temp_sensor_ep, endpoint_t *humidity_sensor_ep)
{
    temp_endpoint_id = endpoint::get_id(temp_sensor_ep);
    humidity_endpoint_id = endpoint::get_id(humidity_sensor_ep);

    i2c_master_init();
    i2c_bme280_init();
    xTaskCreate(&task_bme280_forced_mode, "bme280_forced_mode",  2048, NULL, 6, NULL);
}

