#include <driver/gpio.h>
#include <driver/i2c.h>
#include <esp_err.h>
#include <esp_log.h>
#include <freertos/FreeRTOS.h>
#include <freertos/task.h>
#include <driver/i2c_master.h>
#include <esp_matter_core.h>

#include "sdkconfig.h" // generated by "make menuconfig"
#include "app_priv.h"
#include "bme280.h"

#define TAG_BME280 "APP_BME280"

#define I2C_PORT -1 // autoselect
#define I2C_TIMEOUT -1 // wait forever

#define I2C_BME_ADDRESS 0x76 // default for device
#define I2C_BME_CLK_FREQ 100000
#define I2C_BME_SAMPLE_COUNT 50

// esp i2c handles
static i2c_master_bus_handle_t bus_handle;
bme280_t bme;

// matter data
static uint16_t temp_endpoint_id;
static uint16_t humidity_endpoint_id;

// matter callbacks
using namespace esp_matter;
using namespace esp_matter::endpoint;
using namespace chip::app::Clusters;

// Application cluster specification, 7.18.2.11. Temperature
// represents a temperature on the Celsius scale with a resolution of 0.01°C.
// temp = (temperature in °C) x 100
static void temp_sensor_notification(uint16_t endpoint_id, float temp, void *user_data)
{
    // schedule the attribute update so that we can report it from matter thread
    chip::DeviceLayer::SystemLayer().ScheduleLambda([endpoint_id, temp]() {
        attribute_t * attribute = attribute::get(endpoint_id,
                                                 TemperatureMeasurement::Id,
                                                 TemperatureMeasurement::Attributes::MeasuredValue::Id);

        esp_matter_attr_val_t val = esp_matter_invalid(NULL);
        attribute::get_val(attribute, &val);
        val.val.i16 = static_cast<int16_t>(temp * 100);

        attribute::update(endpoint_id, TemperatureMeasurement::Id, TemperatureMeasurement::Attributes::MeasuredValue::Id, &val);
    });
}

// Application cluster specification, 2.6.4.1. MeasuredValue Attribute
// represents the humidity in percent.
// humidity = (humidity in %) x 100
static void humidity_sensor_notification(uint16_t endpoint_id, float humidity, void *user_data)
{
    // schedule the attribute update so that we can report it from matter thread
    chip::DeviceLayer::SystemLayer().ScheduleLambda([endpoint_id, humidity]() {
        attribute_t * attribute = attribute::get(endpoint_id,
                                                 RelativeHumidityMeasurement::Id,
                                                 RelativeHumidityMeasurement::Attributes::MeasuredValue::Id);

        esp_matter_attr_val_t val = esp_matter_invalid(NULL);
        attribute::get_val(attribute, &val);
        val.val.u16 = static_cast<uint16_t>(humidity * 100);

        attribute::update(endpoint_id, RelativeHumidityMeasurement::Id, RelativeHumidityMeasurement::Attributes::MeasuredValue::Id, &val);
    });
}

void i2c_master_init()
{
    // Create I2C master bus
    i2c_master_bus_config_t i2c_mst_config = {
        .i2c_port = I2C_PORT,
        .sda_io_num = (gpio_num_t)CONFIG_BME280_I2C_SDA_PIN,
        .scl_io_num = (gpio_num_t)CONFIG_BME280_I2C_SCL_PIN,
        .clk_source = I2C_CLK_SRC_DEFAULT,
        .glitch_ignore_cnt = 7,
        .flags {
            // Set this to false if you've wired suitable pullups to scl/sda
            // note that the internal pullup is not strong enough for high speed operation
            .enable_internal_pullup = true,
            .allow_pd = true,
        }
    };

    ESP_LOGD(TAG_BME280, "Attaching to primary I2C bus...");
    ESP_ERROR_CHECK(i2c_new_master_bus(&i2c_mst_config, &bus_handle));

    // Probe for BME device on bus before continuing
    ESP_LOGI(TAG_BME280, "Probing for BME280 on I2C bus at %02X", I2C_BME_ADDRESS);
    ESP_ERROR_CHECK(i2c_master_probe(bus_handle, I2C_BME_ADDRESS, -1));
}

void task_bme280_forced_mode(void *ignore) {
    float t, h;
    while (1) {
        vTaskDelay(pdMS_TO_TICKS(2000)); // 2000 ms update cycle
        esp_err_t err = bme280_read_temp_humidity(&bme, &t, &h);
        if (err == ESP_OK) {
            ESP_LOGI(TAG_BME280, "Temperature:   %.2f C\n", t);
            ESP_LOGI(TAG_BME280, "Humidity   :   %.1f %%RH\n", h);
            esp_matter::lock::chip_stack_lock(portMAX_DELAY);
            temp_sensor_notification(temp_endpoint_id, t, NULL);
            humidity_sensor_notification(humidity_endpoint_id, h, NULL);
            esp_matter::lock::chip_stack_unlock();
        } else {
            ESP_LOGW(TAG_BME280, "Read failed: %s", esp_err_to_name(err));
        }
    }
}

void bme280_app_init(endpoint_t *temp_sensor_ep, endpoint_t *humidity_sensor_ep)
{
    temp_endpoint_id = endpoint::get_id(temp_sensor_ep);
    humidity_endpoint_id = endpoint::get_id(humidity_sensor_ep);

    i2c_master_init();
    ESP_LOGI(TAG_BME280, "Initializing BME280...");
    ESP_ERROR_CHECK(bme280_init(&bme, bus_handle, I2C_BME_ADDRESS, I2C_BME_CLK_FREQ));

    ESP_LOGI(TAG_BME280, "Scheduling BME280 to take regular readings...");
    xTaskCreate(&task_bme280_forced_mode, "bme280_forced_mode",  3072, NULL, 6, NULL);
}

